### ISSUE TITLE
在页面内跳转时，跳转到的内容被 Header 遮挡

### ISSUE THREAD

**Issue by BeiyanYunyi** [project-trans/MtF-wiki#771]
算是一个稍微有点影响体验的细节，查看注释再跳回去的时候会触发。解决方案（CSS）如下：

```css
:target {
  scroll-margin-top: 50px; /* 当前 MtF.wiki 的 Header 高度 */
}
```

因为懒得录 GIF 所以可能表述不太清楚，可以参考 [MDN 的相关条目](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)。
